DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME_P VARCHAR(60) NOT NULL
     , PRICE INT NOT NULL DEFAULT 0
     , IMAGE VARCHAR(200) NOT NULL
     , PRIMARY KEY (ID)
);
